const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{loadApp}=require('./harness.cjs');
const {ctx}=loadApp(),results=[];
const pages=['dashboard','import','masterData','studentProfile','teacherData','data','quality','classes','teachers','departments','school','comparison','value','levels','struggling','reports','customReports','reportDesign','backups','settings'];
for(const mode of ['empty','demo'])for(const page of pages){let index=0;const workspace=mode==='demo'?ctx.zj():ctx.Aj();
 ctx.v={...ctx.v,useState:arg=>{const n=index++,value=n===0?workspace:n===1?structuredClone(workspace.settings):n===3?page:n===6?true:typeof arg==='function'?arg():arg;return [value,()=>{}];},useEffect:()=>{},useMemo:fn=>fn(),useCallback:fn=>fn,useRef:value=>({current:value}),useId:()=>':test:'};
 try{assert.ok(ctx.Nde());results.push({mode,page,status:'pass'});}catch(error){results.push({mode,page,status:'fail',error:error.stack});}
}
// The new archive and report header components are evaluated directly as element trees.
ctx.v={...ctx.v,useState:arg=>[typeof arg==='function'?arg():arg,()=>{}]};
for(const name of ['archive','reportHeader','cloudLogin'])try{const workspace=ctx.zj();assert.ok(name==='cloudLogin'?ctx.SR63.CloudApp():name==='archive'?ctx.SR63.Archives({workspace,snapshots:[],status:'اختبار',bytes:0}):ctx.M9({workspace,title:'ملخص النتائج',subject:'كل المواد',assessment:workspace.settings.exams[0].name}));results.push({name,status:'pass'});}catch(error){results.push({name,status:'fail',error:error.stack});}
try{const workspace=ctx.zj(),page=ctx.SR63.gradeSubjectPages(workspace.rows,workspace.activeExam,'الكل')[0];assert.ok(page);assert.ok(['success','achievement'].includes(page.metricType));assert.ok(ctx.SRGradeSubjectsReport({page,exam:workspace.activeExam,workspace}));results.push({name:'gradeSubjectsReport',status:'pass'});}catch(error){results.push({name:'gradeSubjectsReport',status:'fail',error:error.stack});}
try{const workspace=ctx.zj(),page=ctx.SR63.departmentStatsPages(workspace.rows,workspace.activeExam,'الكل')[0];assert.ok(page);assert.ok(ctx.SRDepartmentStatsReport({page,exam:workspace.activeExam,workspace}));results.push({name:'departmentStatsReport',status:'pass'});}catch(error){results.push({name:'departmentStatsReport',status:'fail',error:error.stack});}
try{const workspace=ctx.zj(),pages=ctx.SR63.gradeSubjectPages(workspace.rows,workspace.activeExam,'الكل');assert.ok(pages.some(p=>p.metricType==='success')&&pages.some(p=>p.metricType==='achievement'));results.push({name:'gradeComparisonDualPages',status:'pass'});}catch(error){results.push({name:'gradeComparisonDualPages',status:'fail',error:error.stack});}

try{const workspace=ctx.zj();ctx.v={...ctx.v,useState:arg=>[typeof arg==='function'?arg():arg,()=>{}],useEffect:()=>{},useMemo:fn=>fn(),useCallback:fn=>fn,useRef:value=>({current:value})};assert.ok(ctx.SR63.Dashboard({workspace,onNavigate:()=>{}}));assert.ok(ctx.SR63.DashboardTrendChart({items:ctx.XA.map(exam=>({exam,metric:ctx.bj(workspace.rows,exam,workspace.settings)})),settings:workspace.settings}));results.push({name:'dashboard69',status:'pass'});}catch(error){results.push({name:'dashboard69',status:'fail',error:error.stack});}
try{const workspace=ctx.zj();ctx.v={...ctx.v,useState:arg=>[typeof arg==='function'?arg():arg,()=>{}],useEffect:()=>{},useMemo:fn=>fn(),useCallback:fn=>fn,useRef:value=>({current:value})};assert.ok(ctx.SR63.MasterData({workspace,setWorkspace:()=>{},onNavigate:()=>{}}));results.push({name:'masterData68',status:'pass'});}catch(error){results.push({name:'masterData68',status:'fail',error:error.stack});}
try{const workspace=ctx.zj();ctx.v={...ctx.v,useState:arg=>[typeof arg==='function'?arg():arg,()=>{}],useEffect:()=>{},useMemo:fn=>fn(),useCallback:fn=>fn,useRef:value=>({current:value})};assert.ok(ctx.SR63.StudentProfile({workspace,onNavigate:()=>{}}));results.push({name:'studentProfile68',status:'pass'});}catch(error){results.push({name:'studentProfile68',status:'fail',error:error.stack});}

try{const reports=fs.readFileSync(path.join(__dirname,'../src/reports.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../src/repair.css'),'utf8');assert.ok(reports.includes('level-overview')&&reports.includes('report-meter')&&reports.includes('فوق المتوسط')&&reports.includes('في المتوسط')&&reports.includes('دون المتوسط'));assert.ok(css.includes('.report-meter')&&css.includes('.level-overview')&&css.includes('.level-macro-badge'));results.push({name:'premiumReportVisuals',status:'pass'});}catch(error){results.push({name:'premiumReportVisuals',status:'fail',error:error.stack});}
try{const reports=fs.readFileSync(path.join(__dirname,'../src/reports.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../src/repair.css'),'utf8'),dash=fs.readFileSync(path.join(__dirname,'../src/dashboard-pro.js'),'utf8');assert.ok(reports.includes('renderReportValue'));assert.ok(css.includes('unified premium reports')&&css.includes('.sr694-insights')&&css.includes('.sr694-donut')&&css.includes('.results-sidebar .sidebar-nav-group:after'));assert.ok(dash.includes('DashboardDonut')&&dash.includes('sr694-insights'));results.push({name:'premiumUnified694',status:'pass'});}catch(error){results.push({name:'premiumUnified694',status:'fail',error:error.stack});}

const report={method:'Element-tree structural checks with inert hooks. No DOM, browser, layout or interaction test.',passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,results};
fs.writeFileSync('tests/output/structure-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.failed)process.exitCode=1;

