/* School Results 6.9.5 — premium executive dashboard and visual analytics. */
SR63.metricTone=function(value,pass){if(value===null||value===undefined)return 'neutral';if(value>=85)return 'excellent';if(value>=70)return 'good';if(value>=pass)return 'mid';return 'low';};
SR63.DashboardTrendChart=function({items,settings}){
  const valid=items.filter(x=>x.metric.evaluated>0),w=720,h=250,pad=34,xStep=(w-pad*2)/Math.max(1,items.length-1),y=value=>h-pad-(Math.max(0,Math.min(100,value??0))/100)*(h-pad*2),points=key=>items.map((x,i)=>x.metric[key]===null?null:[pad+i*xStep,y(x.metric[key])]).filter(Boolean),line=pts=>pts.map(p=>p.join(',')).join(' ');
  return (0,q.jsxs)('div',{className:'sr69-chart-shell',children:[(0,q.jsxs)('div',{className:'sr69-chart-legend',children:[(0,q.jsxs)('span',{className:'success',children:[(0,q.jsx)('i',{}),'نسبة النجاح']}),(0,q.jsxs)('span',{className:'achievement',children:[(0,q.jsx)('i',{}),'نسبة التحصيل']})]}),(0,q.jsxs)('svg',{className:'sr69-line-chart',viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':'اتجاه النجاح والتحصيل عبر الاختبارات',children:[...[0,25,50,75,100].map(v=>(0,q.jsxs)(q.Fragment,{children:[(0,q.jsx)('line',{x1:pad,y1:y(v),x2:w-pad,y2:y(v),className:'grid-line'}),(0,q.jsx)('text',{x:w-pad+8,y:y(v)+4,className:'axis-label',children:`${v}%`})]},v)),valid.length>1&&(0,q.jsx)('polyline',{points:line(points('success')),className:'trend-line success'}),valid.length>1&&(0,q.jsx)('polyline',{points:line(points('achievement')),className:'trend-line achievement'}),...items.flatMap((item,i)=>{const x=pad+i*xStep,arr=[];if(item.metric.success!==null)arr.push((0,q.jsx)('circle',{cx:x,cy:y(item.metric.success),r:5,className:'dot success'},`s-${item.exam}`));if(item.metric.achievement!==null)arr.push((0,q.jsx)('circle',{cx:x,cy:y(item.metric.achievement),r:5,className:'dot achievement'},`a-${item.exam}`));return arr;})]}),(0,q.jsx)('div',{className:'sr69-chart-labels',children:items.map(item=>(0,q.jsxs)('div',{children:[(0,q.jsx)('b',{children:tj(settings,item.exam).name}),(0,q.jsxs)('small',{children:[wj(item.metric.success),' / ',wj(item.metric.achievement)]})]},item.exam))})]});
};

SR63.DashboardDonut=function({metric}){
  const evaluated=Math.max(0,metric.evaluated||0),pass=evaluated?Math.max(0,Math.min(100,(metric.passed||0)/evaluated*100)):0,fail=evaluated?100-pass:0;
  return (0,q.jsxs)('div',{className:'sr694-donut-wrap',children:[(0,q.jsx)('div',{className:'sr694-donut',style:{'--pass':`${pass}%`},children:(0,q.jsxs)('div',{children:[(0,q.jsx)('strong',{children:wj(metric.success)}),(0,q.jsx)('span',{children:'نجاح'})]})}),(0,q.jsxs)('div',{className:'sr694-donut-legend',children:[(0,q.jsxs)('span',{className:'pass',children:[(0,q.jsx)('i',{}),'ناجح ',Q(metric.passed||0)]}),(0,q.jsxs)('span',{className:'fail',children:[(0,q.jsx)('i',{}),'راسب ',Q(metric.failed||0)]}),(0,q.jsxs)('small',{children:['العينة المقيمة: ',Q(evaluated),' نتيجة']})]})]});
};
SR63.DashboardBars=function({groups,workspace,onNavigate}){
  const list=groups.filter(x=>x.metric.achievement!==null).slice(0,7),max=Math.max(100,...list.map(x=>x.metric.achievement??0));
  return (0,q.jsx)('div',{className:'sr69-bars',children:list.length?list.map(item=>{const coord=SR63.subjectCoordinator(workspace,item.name);return (0,q.jsxs)('button',{onClick:()=>onNavigate?.('classes'),className:`sr69-bar-row tone-${SR63.metricTone(item.metric.achievement,workspace.settings.pass)}`,children:[(0,q.jsxs)('span',{className:'sr69-bar-label',children:[(0,q.jsx)('b',{children:item.name}),coord&&(0,q.jsxs)('small',{children:['المنسق: ',coord]})]}),(0,q.jsx)('span',{className:'sr69-bar-track',children:(0,q.jsx)('i',{style:{width:`${Math.max(2,(item.metric.achievement??0)/max*100)}%`}})}),(0,q.jsxs)('strong',{children:[wj(item.metric.achievement),' ',(0,q.jsx)('small',{children:`نجاح ${wj(item.metric.success)}`})]})]},item.name)}):(0,q.jsx)('p',{className:'sr69-empty',children:'لا توجد بيانات كافية للرسم.'})});
};
SR63.DashboardGradeBars=function({rows,workspace}){
  const exam=workspace.activeExam,names=[...new Set(rows.map(r=>gj(r,exam)).filter(Boolean))].sort((a,b)=>SR63.gradeOrder(a)-SR63.gradeOrder(b)),groups=names.map(name=>({name,metric:bj(rows.filter(r=>gj(r,exam)===name),exam,workspace.settings)}));
  return (0,q.jsx)('div',{className:'sr69-grade-bars',children:groups.length?groups.map(g=>(0,q.jsxs)('article',{children:[(0,q.jsxs)('header',{children:[(0,q.jsx)('b',{children:g.name}),(0,q.jsxs)('span',{children:[Q(g.metric.students),' طالب']})]}),(0,q.jsxs)('div',{className:'sr69-grade-pair',children:[(0,q.jsx)('div',{children:(0,q.jsx)('i',{style:{height:`${Math.max(3,g.metric.success??0)}%`},className:'success'})}),(0,q.jsx)('div',{children:(0,q.jsx)('i',{style:{height:`${Math.max(3,g.metric.achievement??0)}%`},className:'achievement'})})]}),(0,q.jsxs)('footer',{children:[(0,q.jsx)('span',{children:`نجاح ${wj(g.metric.success)}`}),(0,q.jsx)('span',{children:`تحصيل ${wj(g.metric.achievement)}`})]})]},g.name)):(0,q.jsx)('p',{className:'sr69-empty',children:'لا توجد صفوف ضمن الفلاتر الحالية.'})});
};
SR63.Dashboard=function({workspace,onNavigate}){
  const c=(0,v.useMemo)(()=>SR63.ensureCatalog(workspace),[workspace]),[grade,setGrade]=(0,v.useState)('الكل'),[className,setClass]=(0,v.useState)('الكل'),[subject,setSubject]=(0,v.useState)('الكل'),[teacher,setTeacher]=(0,v.useState)('الكل'),model=(0,v.useMemo)(()=>SR63.dashboardModel(workspace,{grade,className,subject,teacher}),[workspace,grade,className,subject,teacher]),metric=model.metric;
  const filter=(label,value,setter,items)=>(0,q.jsxs)('label',{className:'sr69-filter',children:[(0,q.jsx)('span',{children:label}),(0,q.jsx)('select',{value,onChange:e=>setter(e.target.value),children:[(0,q.jsx)('option',{value:'الكل',children:`كل ${label}`}),items.map(x=>(0,q.jsx)('option',{value:x,children:x},x))]})]});
  const rowForExam=exam=>workspace.rows.filter(row=>(grade==='الكل'||gj(row,exam)===grade)&&(className==='الكل'||hj(row,exam)===className)&&(subject==='الكل'||row.subject===subject)&&(teacher==='الكل'||mj(row,exam)===teacher)),examTrend=XA.map(exam=>({exam,metric:bj(rowForExam(exam),exam,workspace.settings)})),reportReady=model.issues.critical===0&&model.coverage.missing===0&&metric.evaluated>0,completion=model.rows.length?Math.min(100,metric.evaluated/model.rows.length*100):0,subjectBest=model.subjectGroups.slice().sort((a,b)=>(b.metric.achievement??-1)-(a.metric.achievement??-1)),teacherBest=model.teacherGroups.slice().sort((a,b)=>(b.metric.achievement??-1)-(a.metric.achievement??-1)).slice(0,6),lowSubjects=model.subjectGroups.slice().sort((a,b)=>(a.metric.achievement??999)-(b.metric.achievement??999)).slice(0,5),bestSubject=subjectBest.find(x=>x.metric.achievement!==null),bestTeacher=teacherBest.find(x=>x.metric.achievement!==null),weakSubject=lowSubjects.find(x=>x.metric.achievement!==null),openStudent=s=>{SR63.openStudentId=s.studentId;onNavigate('studentProfile');},cellTone=value=>SR63.metricTone(value,workspace.settings.pass);
  const kpis=[
    {label:'نسبة النجاح',value:wj(metric.success),hint:`${metric.passed} نتيجة ناجحة من ${metric.evaluated}`,tone:SR63.metricTone(metric.success,workspace.settings.pass)},
    {label:'نسبة التحصيل',value:wj(metric.achievement),hint:tj(workspace.settings,workspace.activeExam).name,tone:SR63.metricTone(metric.achievement,workspace.settings.pass)},
    {label:'الطلاب',value:Q(metric.students),hint:`${Q(metric.evaluated)} نتيجة مقيمة`,tone:'navy'},
    {label:'اكتمال النتائج',value:wj(completion,0),hint:`${model.rows.length-metric.evaluated} نتيجة غير مكتملة`,tone:completion>=95?'excellent':'mid'},
    {label:'جاهزية التقارير',value:reportReady?'جاهز':'يحتاج مراجعة',hint:reportReady?'لا توجد عوائق حرجة':`${model.issues.critical} مشكلة حرجة · ${model.coverage.missing} تكليف ناقص`,tone:reportReady?'excellent':'low'}
  ];
  return (0,q.jsxs)('div',{className:'sr69-dashboard',children:[
    (0,q.jsxs)('section',{className:'sr69-command-hero',children:[(0,q.jsxs)('div',{className:'sr69-hero-main',children:[(0,q.jsx)('span',{className:'sr69-eyebrow',children:'مركز القيادة والتحليل'}),(0,q.jsx)('h1',{children:workspace.settings.schoolName}),(0,q.jsxs)('p',{children:['قراءة لحظية للنتائج والهيكل الأكاديمي · ',workspace.settings.academicYear]}),(0,q.jsxs)('div',{className:'sr69-hero-actions',children:[(0,q.jsx)('button',{className:'primary',onClick:()=>onNavigate('import'),children:'رفع نتائج جديدة'}),(0,q.jsx)('button',{onClick:()=>onNavigate('masterData'),children:'إدارة الهيكل الأكاديمي'}),(0,q.jsx)('button',{onClick:()=>onNavigate('reports'),children:'فتح التقارير'})]})]}),(0,q.jsxs)('aside',{className:'sr69-cloud-summary',children:[(0,q.jsxs)('div',{className:'sr69-cloud-status',children:[(0,q.jsx)('i',{className:SR63.storage.blocked?'bad':SR63.storage.pending?'pending':'ok'}),(0,q.jsx)('span',{children:SR63.storage.blocked?'الحفظ السحابي متوقف':SR63.storage.pending?'جارٍ حفظ التغييرات':'Supabase متزامن'})]}),(0,q.jsxs)('strong',{children:['Revision ',SR63.storage.revision??'—']}),(0,q.jsx)('small',{children:SR63.storage.savedAt?`آخر حفظ ${new Date(SR63.storage.savedAt).toLocaleString('ar-EG')}`:'لم يتم الحفظ بعد'}),(0,q.jsx)('small',{children:SR63.storage.error||'قاعدة النتائج السحابية متاحة'})]})]}),
    (0,q.jsx)('section',{className:'sr69-kpi-strip',children:kpis.map((item,index)=>(0,q.jsxs)('article',{className:`tone-${item.tone}`,children:[(0,q.jsx)('span',{children:item.label}),(0,q.jsx)('strong',{children:item.value}),(0,q.jsx)('small',{children:item.hint}),(0,q.jsx)('i',{className:'sr69-kpi-spark',style:{'--spark':`${Math.min(100,index===0?(metric.success??0):index===1?(metric.achievement??0):index===2?Math.min(100,metric.students*3):index===3?completion:reportReady?100:45)}%`}})]},item.label))}),
    (0,q.jsxs)('section',{className:'sr69-filterbar',children:[filter('الصف',grade,setGrade,c.grades.filter(g=>g.active!==false).map(g=>g.name)),filter('الشعبة',className,setClass,c.classes.filter(x=>x.active!==false&&(grade==='الكل'||x.grade===grade)).map(x=>x.className)),filter('المادة',subject,setSubject,c.subjects.filter(s=>s.active!==false).map(s=>s.name)),filter('المعلم',teacher,setTeacher,c.teachers.filter(t=>t.active!==false).map(t=>t.teacher)),(0,q.jsx)('button',{className:'reset',onClick:()=>{setGrade('الكل');setClass('الكل');setSubject('الكل');setTeacher('الكل')},children:'إعادة الضبط'})]}),
    (0,q.jsx)('section',{className:'sr694-insights',children:[{label:'أفضل مادة',value:bestSubject?.name||'—',metric:bestSubject?.metric?.achievement,hint:bestSubject?`تحصيل ${wj(bestSubject.metric.achievement)}`:'لا توجد بيانات'},{label:'أفضل أداء معلم',value:bestTeacher?.name||'—',metric:bestTeacher?.metric?.achievement,hint:bestTeacher?`نجاح ${wj(bestTeacher.metric.success)}`:'لا توجد بيانات'},{label:'أولوية المتابعة',value:weakSubject?.name||'—',metric:weakSubject?.metric?.achievement,hint:weakSubject?`تحصيل ${wj(weakSubject.metric.achievement)}`:'لا توجد بيانات'},{label:'طلاب تحت حد النجاح',value:Q(model.struggling.length),metric:model.struggling.length?Math.max(0,100-model.struggling.length*5):100,hint:model.struggling.length?'تحتاج متابعة مباشرة':'لا توجد حالات ضمن الفلاتر'}].map((x,i)=>(0,q.jsxs)('article',{className:`insight-${i}`,children:[(0,q.jsx)('span',{children:x.label}),(0,q.jsx)('b',{children:x.value}),(0,q.jsx)('small',{children:x.hint}),(0,q.jsx)('i',{style:{width:`${SR63.clampPercent(x.metric??0)}%`}})]},x.label))}),
    (0,q.jsxs)('section',{className:'sr69-top-charts sr694-top-charts',children:[(0,q.jsxs)('article',{className:'sr69-panel sr69-trend-panel',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'الاتجاه العام'}),(0,q.jsx)('h2',{children:'تطور النجاح والتحصيل عبر الاختبارات'})]}),(0,q.jsx)('b',{children:tj(workspace.settings,workspace.activeExam).name})]}),(0,q.jsx)(SR63.DashboardTrendChart,{items:examTrend,settings:workspace.settings})]}),(0,q.jsxs)('article',{className:'sr69-panel sr69-grade-panel',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'مقارنة الصفوف'}),(0,q.jsx)('h2',{children:'أداء الصفوف في الاختبار النشط'})]}),(0,q.jsx)('small',{children:'نجاح / تحصيل'})]}),(0,q.jsx)(SR63.DashboardGradeBars,{rows:model.rows,workspace})]}),(0,q.jsxs)('article',{className:'sr69-panel sr694-donut-panel',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'توزيع النتائج'}),(0,q.jsx)('h2',{children:'ناجح مقابل راسب'})]}),(0,q.jsx)('small',{children:Q(metric.evaluated)+' نتيجة'})]}),(0,q.jsx)(SR63.DashboardDonut,{metric})]})]}),
    (0,q.jsxs)('section',{className:'sr69-mid-grid',children:[(0,q.jsxs)('article',{className:'sr69-panel',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'المواد'}),(0,q.jsx)('h2',{children:'ترتيب المواد حسب التحصيل'})]}),(0,q.jsx)('button',{onClick:()=>onNavigate('departments'),children:'تحليل أوسع'})]}),(0,q.jsx)(SR63.DashboardBars,{groups:subjectBest,workspace,onNavigate})]}),(0,q.jsxs)('article',{className:'sr69-panel sr69-readiness',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'سلامة البيانات'}),(0,q.jsx)('h2',{children:'جاهزية الاعتماد والتقارير'})]})]}),(0,q.jsxs)('div',{className:'sr69-ring-grid',children:[(0,q.jsxs)('div',{className:'sr69-ring',style:{'--pct':`${Math.round(model.coverage.percent)}%`},children:[(0,q.jsx)('strong',{children:wj(model.coverage.percent,0)}),(0,q.jsx)('span',{children:'التكليفات'})]}),(0,q.jsxs)('div',{className:'sr69-ring secondary',style:{'--pct':`${Math.round(completion)}%`},children:[(0,q.jsx)('strong',{children:wj(completion,0)}),(0,q.jsx)('span',{children:'النتائج'})]})]}),(0,q.jsxs)('div',{className:'sr69-readiness-list',children:[(0,q.jsxs)('button',{onClick:()=>onNavigate('quality'),children:[(0,q.jsx)('span',{children:'مشكلات حرجة'}),(0,q.jsx)('b',{children:Q(model.issues.critical)})]}),(0,q.jsxs)('button',{onClick:()=>onNavigate('masterData'),children:[(0,q.jsx)('span',{children:'تكليفات بلا معلم'}),(0,q.jsx)('b',{children:Q(model.coverage.missing)})]}),(0,q.jsxs)('button',{onClick:()=>onNavigate('studentProfile'),children:[(0,q.jsx)('span',{children:'طلاب يحتاجون دعمًا'}),(0,q.jsx)('b',{children:Q(model.struggling.length)})]})]})]})]}),
    (0,q.jsxs)('section',{className:'sr69-mid-grid sr69-second-row',children:[(0,q.jsxs)('article',{className:'sr69-panel',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'المتابعة'}),(0,q.jsx)('h2',{children:'مواد تحتاج تدخلًا سريعًا'})]})]}),(0,q.jsx)('div',{className:'sr69-watch-list',children:lowSubjects.map(item=>(0,q.jsxs)('div',{className:`tone-${cellTone(item.metric.achievement)}`,children:[(0,q.jsxs)('span',{children:[(0,q.jsx)('b',{children:item.name}),(0,q.jsx)('small',{children:SR63.subjectCoordinator(workspace,item.name)?`المنسق: ${SR63.subjectCoordinator(workspace,item.name)}`:'منسق المادة غير محدد'})]}),(0,q.jsx)('strong',{children:wj(item.metric.achievement)})]},item.name))})]}),(0,q.jsxs)('article',{className:'sr69-panel',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'المعلمون'}),(0,q.jsx)('h2',{children:'أعلى أداء للمعلمين'})]}),(0,q.jsx)('button',{onClick:()=>onNavigate('teachers'),children:'عرض التحليل'})]}),(0,q.jsx)('div',{className:'sr69-teacher-grid',children:teacherBest.map(item=>(0,q.jsxs)('div',{children:[(0,q.jsx)('b',{children:item.name}),(0,q.jsx)('strong',{children:wj(item.metric.achievement)}),(0,q.jsxs)('small',{children:['نجاح ',wj(item.metric.success),' · ',Q(item.metric.evaluated),' نتيجة']})]},item.name))})]})]}),
    (0,q.jsxs)('section',{className:'sr69-bottom-grid',children:[(0,q.jsxs)('article',{className:'sr69-panel',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'الخريطة الحرارية'}),(0,q.jsx)('h2',{children:'الشعب × المواد'})]})]}),(0,q.jsx)('div',{className:'sr68-table-wrap',children:model.classes.length&&model.subjects.length?(0,q.jsxs)('table',{className:'sr68-heatmap sr69-heatmap',children:[(0,q.jsx)('thead',{children:(0,q.jsxs)('tr',{children:[(0,q.jsx)('th',{children:'الشعبة'}),model.subjects.map(s=>(0,q.jsx)('th',{children:s},s))]})}),(0,q.jsx)('tbody',{children:model.classes.map(cls=>(0,q.jsxs)('tr',{children:[(0,q.jsx)('th',{children:cls}),model.subjects.map(sub=>{const h=model.heat.find(x=>x.className===cls&&x.subject===sub),value=h?.metric.achievement??null;return (0,q.jsx)('td',{className:`tone-${cellTone(value)}`,title:value===null?'لا توجد بيانات':`نجاح ${wj(h.metric.success)} · تحصيل ${wj(value)}`,children:wj(value,0)},sub)})]},cls))})]}):(0,q.jsx)('p',{className:'sr69-empty',children:'لا توجد بيانات كافية للخريطة الحرارية.'})})]}),(0,q.jsxs)('article',{className:'sr69-panel',children:[(0,q.jsxs)('header',{children:[(0,q.jsxs)('div',{children:[(0,q.jsx)('span',{children:'الطلاب'}),(0,q.jsx)('h2',{children:'الأولوية للدعم والمتابعة'})]}),(0,q.jsx)('button',{onClick:()=>onNavigate('struggling'),children:'كل المتعثرين'})]}),(0,q.jsx)('div',{className:'sr69-students',children:model.struggling.length?model.struggling.map(s=>(0,q.jsxs)('button',{onClick:()=>openStudent(s),children:[(0,q.jsxs)('span',{children:[(0,q.jsx)('b',{children:s.studentName}),(0,q.jsxs)('small',{children:[s.studentId,' · ',s.className]})]}),(0,q.jsx)('strong',{children:wj(s.average)})]},s.studentId)):(0,q.jsx)('p',{className:'sr69-empty',children:'لا يوجد طلاب تحت حد النجاح ضمن الفلاتر الحالية.'})})]})]})
  ]});
};
